// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface ItemPasswordRecipe {
    digits?: pulumi.Input<boolean>;
    length?: pulumi.Input<number>;
    letters?: pulumi.Input<boolean>;
    symbols?: pulumi.Input<boolean>;
}

export interface ItemSection {
    fields?: pulumi.Input<pulumi.Input<inputs.ItemSectionField>[]>;
    id?: pulumi.Input<string>;
    label: pulumi.Input<string>;
}

export interface ItemSectionField {
    id?: pulumi.Input<string>;
    label: pulumi.Input<string>;
    passwordRecipe?: pulumi.Input<inputs.ItemSectionFieldPasswordRecipe>;
    purpose?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

export interface ItemSectionFieldPasswordRecipe {
    digits?: pulumi.Input<boolean>;
    length?: pulumi.Input<number>;
    letters?: pulumi.Input<boolean>;
    symbols?: pulumi.Input<boolean>;
}
