// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface GetItemSection {
    fields: outputs.GetItemSectionField[];
    id: string;
    label: string;
}

export interface GetItemSectionField {
    id: string;
    label: string;
    purpose: string;
    type: string;
    value: string;
}

export interface ItemPasswordRecipe {
    digits?: boolean;
    length?: number;
    letters?: boolean;
    symbols?: boolean;
}

export interface ItemSection {
    fields?: outputs.ItemSectionField[];
    id: string;
    label: string;
}

export interface ItemSectionField {
    id: string;
    label: string;
    passwordRecipe?: outputs.ItemSectionFieldPasswordRecipe;
    purpose?: string;
    type?: string;
    value: string;
}

export interface ItemSectionFieldPasswordRecipe {
    digits?: boolean;
    length?: number;
    letters?: boolean;
    symbols?: boolean;
}
