// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getItem(args: GetItemArgs, opts?: pulumi.InvokeOptions): Promise<GetItemResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("onepassword:index/getItem:getItem", {
        "title": args.title,
        "uuid": args.uuid,
        "vault": args.vault,
    }, opts);
}

/**
 * A collection of arguments for invoking getItem.
 */
export interface GetItemArgs {
    title?: string;
    uuid?: string;
    vault: string;
}

/**
 * A collection of values returned by getItem.
 */
export interface GetItemResult {
    readonly category: string;
    readonly database: string;
    readonly hostname: string;
    readonly id: string;
    readonly password: string;
    readonly port: string;
    readonly sections: outputs.GetItemSection[];
    readonly tags: string[];
    readonly title: string;
    readonly type: string;
    readonly url: string;
    readonly username: string;
    readonly uuid: string;
    readonly vault: string;
}
